/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

import controlador.GestorPacienteControl;

/**
 *
 * @author casa aseo
 */
public class ConsPacienteInternalFrame extends JInternalFrame {

	public GestorPacienteControl gestorpacienteControl;

	private final DefaultTableModel tabla;

	public ConsPacienteInternalFrame() {
		initComponents();
		gestorpacienteControl = new GestorPacienteControl(this);
		String titulosTabla[] = { "Identificacion", "Nombres", "Apellidos", "Fecha_Nacimiento", "Sexo", "Celular",
				"Direccion", "Correo" };
		tabla = new DefaultTableModel(null, titulosTabla);
		tbl_datos.setModel(tabla);
		btn_aceptar.addActionListener(gestorpacienteControl);
	}

	public DefaultTableModel getTableModel() {
		return tabla;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new ButtonGroup();
		rdb_identificacion = new JRadioButton();
		rdb_nombres = new JRadioButton();
		rdb_apellidos = new JRadioButton();
		rdb_genero = new JRadioButton();
		rdb_celular = new JRadioButton();
		rdb_direccion = new JRadioButton();
		rdb_correo = new JRadioButton();
		jLabel1 = new JLabel();
		txt_valor = new JTextField();
		btn_aceptar = new JButton();
		jScrollPane1 = new JScrollPane();
		tbl_datos = new JTable();
		jButton2 = new JButton();

		buttonGroup1.add(rdb_identificacion);
		rdb_identificacion.setText("Id");

		buttonGroup1.add(rdb_nombres);
		rdb_nombres.setText("Nombres");

		buttonGroup1.add(rdb_apellidos);
		rdb_apellidos.setText("Apellidos");

		buttonGroup1.add(rdb_genero);
		rdb_genero.setText("Sexo");

		buttonGroup1.add(rdb_celular);
		rdb_celular.setText("Celular");

		buttonGroup1.add(rdb_direccion);
		rdb_direccion.setText("Direccion");

		buttonGroup1.add(rdb_correo);
		rdb_correo.setText("Correo");

		jLabel1.setText("Valor a Buscar");

		txt_valor.setText("");
		txt_valor.setName("ValorTxt"); // NOI18N
		txt_valor.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				txt_valorActionPerformed(evt);
			}
		});

		btn_aceptar.setText("Aceptar");
		btn_aceptar.setName("AceptarBtn"); // NOI18N

		jScrollPane1.setBackground(new Color(51, 0, 255));
		jScrollPane1.setName("ResultadosTbl"); // NOI18N

		tbl_datos.setBackground(new Color(0, 255, 255));
		tbl_datos
				.setModel(new DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tbl_datos);

		jButton2.setText("Cerrar");
		jButton2.setName("CerrarBtn"); // NOI18N

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(txt_valor, GroupLayout.PREFERRED_SIZE, 314, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED))
						.addGroup(GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addComponent(rdb_identificacion).addGap(18, 18, 18)
										.addComponent(rdb_nombres)
										.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(rdb_apellidos).addGap(26, 26, 26).addComponent(rdb_genero)
										.addGap(26, 26, 26).addComponent(rdb_celular).addGap(35, 35, 35)))
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(btn_aceptar)
						.addGroup(layout.createSequentialGroup().addComponent(rdb_direccion).addGap(18, 18, 18)
								.addComponent(rdb_correo)))
				.addContainerGap(8, Short.MAX_VALUE))
				.addGroup(GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(78, 78, 78))
				.addGroup(GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton2).addGap(23, 23, 23)));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(rdb_identificacion)
						.addComponent(rdb_nombres).addComponent(rdb_apellidos).addComponent(rdb_genero)
						.addComponent(rdb_celular).addComponent(rdb_direccion).addComponent(rdb_correo))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(txt_valor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(btn_aceptar))
				.addGap(27, 27, 27)
				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE).addComponent(jButton2)
				.addGap(19, 19, 19)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txt_valorActionPerformed(ActionEvent evt) {// GEN-FIRST:event_txt_valorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_valorActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public JButton btn_aceptar;
	private ButtonGroup buttonGroup1;
	private JButton jButton2;
	private JLabel jLabel1;
	private JScrollPane jScrollPane1;
	public JRadioButton rdb_apellidos;
	public JRadioButton rdb_celular;
	public JRadioButton rdb_correo;
	public JRadioButton rdb_direccion;
	public JRadioButton rdb_genero;
	public JRadioButton rdb_identificacion;
	public JRadioButton rdb_nombres;
	public JTable tbl_datos;
	public JTextField txt_valor;
	// End of variables declaration//GEN-END:variables
}
