package vista;

import java.awt.EventQueue;

import javax.swing.JInternalFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import controlador.ActulPacienteController;
import controlador.ElimPacienteController;

public class ElimPacienteJInternalFrame extends JInternalFrame {
	private final ElimPacienteController pacienteControlador;

	/**
	 * Launch the application.
	 */

	public ElimPacienteJInternalFrame() {
		initComponents();
		pacienteControlador = new ElimPacienteController(this);
		jButton2.addActionListener(pacienteControlador);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setTitle("Eliminar  Pacientes");
		setName("EliminatBtn");

		jLabel1.setText("Identificacion");

		jTextField1.setText("jTextField1");
		jTextField1.setName("ValorTxt2"); // NOI18N

		jButton1.setText("Aceptar");
		jButton1.setName("AceptarBtn"); // NOI18N

		jButton2.setText("Eliminar");
		jButton2.setName("EliminarBtn"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(17)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jTextField1).addGap(18)
								.addComponent(jButton1))
						.addGroup(layout.createSequentialGroup().addGap(259).addComponent(jButton2,
								GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(47, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(48)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel1)
								.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton1))
						.addGap(99).addComponent(jButton2).addContainerGap(118, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

// Variables declaration - do not modify                     
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	public javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	public javax.swing.JTextField jTextField1;
// End of variables declaration                   
}
